language: haskell
install:
        - cabal install --only-dependencies
        - cabal configure
        - cabal build
script:
        - dist/build/bookmarks-lib-test/bookmarks-lib-test #cabal test
        - dist/build/bookmarks-lib-doctest/bookmarks-lib-doctest #cabal test
