name: Haskell CI with Stack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # don't cancel other jobs if one fails
      matrix:
        resolver: ["nightly"] #"lts-18", "lts-20", "nightly"]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          persist-credentials: false

      - name: Remove .git
        run: rm -rf .git

      - name: Setup Haskell Compiler (stack)
        id: setup-haskell
        uses: haskell/actions/setup@93635e8c4ac823f55cf3444537a63d3f2fd589de # v2.1.0
        with:
          enable-stack: true
          stack-no-global: true

      - name: Echo some vars
        run: echo ${{ steps.setup-haskell.outputs.stack-root }}

      - name: Cache .stack-work
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ./.stack-work
          key: stack-work

      - name: Cache ~/.stack
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ${{ steps.setup-haskell.outputs.stack-root }}
          key: stack-root

      - name: Get dependencies
        run: stack --resolver=${{ matrix.resolver }} build --only-dependencies --test --bench --no-run-tests --no-run-benchmarks

      - name: List everything (2)
        run: |
          find .stack-work -type f | sort | xargs sha256sum > sw_2
          find ${{ steps.setup-haskell.outputs.stack-root }} -type f | sort | xargs sha256sum > sr_2
          diff -u /dev/null sr_2 || true

      - name: Build code
        run: stack --resolver=${{ matrix.resolver }} build --test --bench --no-run-tests --no-run-benchmarks

      - name: List everything (3)
        run: |
          find .stack-work -type f | sort | xargs sha256sum > sw_3
          find ${{ steps.setup-haskell.outputs.stack-root }} -type f | sort | xargs sha256sum > sr_3
          diff -u sw_2 sw_3 || true
          echo "===="
          diff -u sr_2 sr_3 || true

      - name: Test code
        run: stack --resolver=${{ matrix.resolver }} test

      - name: List everything (4)
        run: |
          find .stack-work -type f | sort | xargs sha256sum > sw_4
          find ${{ steps.setup-haskell.outputs.stack-root }} -type f | sort | xargs sha256sum > sr_4
          diff -u sw_3 sw_4 || true
          echo "===="
          diff -u sr_3 sr_4 || true

      - name: Benchmark code
        run: stack --resolver=${{ matrix.resolver }} bench

      - name: List everything (5)
        run: |
          find .stack-work -type f | sort | xargs sha256sum > sw_5
          find ${{ steps.setup-haskell.outputs.stack-root }} -type f | sort | xargs sha256sum > sr_5
          diff -u sw_4 sw_5 || true
          echo "===="
          diff -u sr_4 sr_5 || true
