name: Haskell CI with Stack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: Test job
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # TODO(mihaimaruseac): Only nightly, given cache size
        resolver: ["nightly"] #"lts-18", "lts-20", "nightly"]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          persist-credentials: false

      - name: Setup Haskell Compiler (stack)
        id: setup-haskell
        uses: haskell/actions/setup@93635e8c4ac823f55cf3444537a63d3f2fd589de # v2.1.0
        with:
          enable-stack: true
          stack-no-global: true

      - name: Echo some vars
        run: echo ${{ steps.setup-haskell.outputs.stack-root }}

      - name: Cache .stack-work
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: .stack-work
          # TODO(mihaimaruseac): Group cabal and stack.yaml
          # TODO(mihaimaruseac): package.yaml?
          key: stack-work-${{ matrix.os }}-${{ matrix.resolver }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('src*') }}
          restore-keys: |
            stack-work-${{ matrix.os }}-${{ matrix.resolver }}-${{ hashFiles('**/*.cabal') }}-
            stack-work-${{ matrix.os }}-${{ matrix.resolver }}-

      - name: Cache ~/.stack
        uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d # v3.2.2
        with:
          path: ${{ steps.setup-haskell.outputs.stack-root }}
          key: stack-root-${{ matrix.os }}-${{ matrix.resolver }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: stack-root-${{ matrix.os }}-${{ matrix.resolver }}-

      - name: Get dependencies
        run: stack --resolver=${{ matrix.resolver }} build --only-dependencies --test --bench --no-run-tests --no-run-benchmarks

      - name: Build code
        run: stack --resolver=${{ matrix.resolver }} build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test code
        run: stack --resolver=${{ matrix.resolver }} test

      - name: Benchmark code
        run: stack --resolver=${{ matrix.resolver }} bench
