name: Haskell CI with Stack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # don't cancel other jobs if one fails
      matrix:
        resolver: ["nightly"] #"lts-18", "lts-20", "nightly"]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          persist-credentials: false

      - name: Remove .git
        run: rm -rf .git

      - name: Setup Haskell Compiler (stack)
        id: setup-haskell
        uses: haskell/actions/setup@93635e8c4ac823f55cf3444537a63d3f2fd589de # v2.1.0
        with:
          enable-stack: true
          stack-no-global: true

      - name: Echo some vars
        run: echo ${{ steps.setup-haskell.outputs.stack-root }}

      - name: Get dependencies
        run: stack --resolver=${{ matrix.resolver }} build --only-dependencies --test --bench --no-run-tests --no-run-benchmarks

      - name: List everything (2)
        run: |
          tree -alps .stack-work
          echo "===="
          tree -alps ${{ steps.setup-haskell.outputs.stack-root }}

      - name: Build
        run: stack --resolver=${{ matrix.resolver }} build --test --bench --no-run-tests --no-run-benchmarks

      - name: List everything (3)
        run: |
          tree -alps .stack-work
          echo "===="
          tree -alps ${{ steps.setup-haskell.outputs.stack-root }}

      - name: Test
        run: stack --resolver=${{ matrix.resolver }} test

      - name: List everything (4)
        run: |
          tree -alps .stack-work
          echo "===="
          tree -alps ${{ steps.setup-haskell.outputs.stack-root }}

      - name: Bench
        run: stack --resolver=${{ matrix.resolver }} bench

      - name: List everything (5)
        run: |
          tree -alps .stack-work
          echo "===="
          tree -alps ${{ steps.setup-haskell.outputs.stack-root }}
